#!/usr/bin/env bash
# Installs nginx web server

apt-get update
apt-get install -y nginx
service nginx start
mkdir -p /var/www/html
echo "Hello, World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/4-not_found_page_404.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html;
    location /redirect_me {
        return 301 https://github.com/Mark-shija;
    }
    error_page 404 /4-not_found_page_404.html;
    location = /4-not_found_page_404.html{
        root /var/www/html;
        internal;
    }
}" | sudo tee /etc/nginx/sites-available/default
service nginx restart
