#!/usr/bin/env bash
# Script to display "Best School" 10 times, and "Hi" on the 9th iteration.

COUNTER=0
while [ $COUNTER -lt 11 ]
do
    if [ $COUNTER = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    let COUNTER+=1
done
