#!/usr/bin/env bash
# Script to display "Best School" 10 times, and "Hi" on the 9th iteration.

COUNTER=0
while [ $COUNTER -lt 10 ]
do
    if [ $COUNTER -eq 8 ]; then
        echo "Hi"
    fi
    echo "Best School"
    ((COUNTER++))
done
