#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
cp /etc/hosts ~/hosts.changed
echo "127.0.0.2		localhost" > ~/hosts.changed
echo "8.8.8.8		facebook.com" >> ~/hosts.changed
cp -f ~/hosts.changed /etc/hosts
